### ISSUE TITLE
device mismatch in train() function

### ISSUE THREAD

**Issue by julssg** [MatthewWilletts/idontneedu#1]
When I try to run the code on my gpu, in the runner _cluster_real_data_runner.py_, inside the _train()_ function, an error occurs since model and data seem to be not on the same device:

  ```
`$ python -u main.py --config mnist_mlp.yaml --n-sims 10 --representation -z 50 
  Running on gpu:0
  
  [...]
  
  making VaDEFullMLP
  ncomp:  40
  making MLPs
  Traceback (most recent call last):
  File "main.py", line 245, in <module>
  sys.exit(main())
  File "main.py", line 148, in main
  compute_representations(new_args, config)
  File "C:\Users\julia\Documents\Masterarbeit\masterthesis_code\idontneedu\runners\cluster_real_data_runner.py", line 312, in compute_representations
  ELBO_train = train(args, config, conditional=conditional, return_elbo=True)
  File "C:\Users\julia\Documents\Masterarbeit\masterthesis_code\idontneedu\runners\cluster_real_data_runner.py", line 168, in train
  data_dependent_init(model, {'x': t})
  File "C:\Users\julia\anaconda3\lib\site-packages\boilr\nn\init.py", line 117, in data_dependent_init
  model(**model_input_dict)  # dry-run
  File "C:\Users\julia\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
  return forward_call(*input, **kwargs)
  File "C:\Users\julia\Documents\Masterarbeit\masterthesis_code\idontneedu\models\nde.py", line 367, in forward
  mu, logv = self.encode(x)
  File "C:\Users\julia\Documents\Masterarbeit\masterthesis_code\idontneedu\models\nde.py", line 475, in encode
  return self.encoder(x.view(-1, self.input_size))
  File "C:\Users\julia\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
  return forward_call(*input, **kwargs)
  File "C:\Users\julia\Documents\Masterarbeit\masterthesis_code\idontneedu\models\nets.py", line 282, in forward
  output = self.linear(output)
  File "C:\Users\julia\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
  return forward_call(*input, **kwargs)
  File "C:\Users\julia\anaconda3\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
  input = module(input)
  File "C:\Users\julia\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1071, in _call_impl
  result = forward_call(*input, **kwargs)
  File "C:\Users\julia\anaconda3\lib\site-packages\torch\nn\modules\linear.py", line 96, in forward
  return F.linear(input, self.weight, self.bias)
  File "C:\Users\julia\anaconda3\lib\site-packages\torch\nn\functional.py", line 1847, in linear
  return torch._C._nn.linear(input, weight, bias)
  RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument mat1 in method wrapper_addmm)`
```

**Comment by julssg** [comment]
**Suggested fix:**
In \runners\cluster_real_data_runner.py line 157:

```
# model = get_dgm(args, config, good_dims)

model = get_dgm(args, config, good_dims).to(config.device)
```
