### ISSUE TITLE
device mismatch after loading checkpoint in sample() 

### ISSUE THREAD

**Issue by julssg** [MatthewWilletts/idontneedu#2]
When checkpoint exists and try to load that, I see a device mismatch  when sampling with VaDEFullMLP:

```
$python -u main.py --config mnist_mlp.yaml --n-sims 10 --representation -z 50
Running on gpu:0

loading model weights from: run\checkpoints\MNIST\representationVADE50mlp\seed0\checkpoint.pth
making VaDEFullMLP
ncomp:  40
making MLPs
Traceback (most recent call last):
  File "main.py", line 245, in <module>    sys.exit(main())
  File "main.py", line 148, in main
    compute_representations(new_args, config)
  File "C:\Users\julia\Documents\Masterarbeit\masterthesis_code\idontneedu\runners\cluster_real_data_runner.py", line 326, in compute_rep
resentations    samples = f.sample(10, per_comp=True)
  File "C:\Users\julia\Documents\Masterarbeit\masterthesis_code\idontneedu\models\nde.py", line 510, in sample
    loc = y_samples @ self.mu_p_z.permute(1,0)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for
argument mat2 in method wrapper_mm)
```

**Comment by julssg** [comment]
One fix could be to:

in \models\nde.py line 510

define self.device in _init_
```
#             y_samples = torch.tensor(np.eye(self.num_components, dtype=np.float32))
            y_samples = torch.tensor(np.eye(self.num_components, dtype=np.float32)).to(self.device)
```

Then a new error occurs that 'output' and 'f' are not on the same device.... fix could be:
in \models\nde.py line 519:

```
#                 output = torch.zeros(f.shape)
                output = torch.zeros(f.shape).to(self.device)
```

But I am not sure whether this is pretty...
